
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EntityFrameworkModel
{

using System;
    using System.Collections.Generic;
    
public partial class Koszyk
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Koszyk()
    {

        this.Koszyk_Podzespol = new HashSet<Koszyk_Podzespol>();

    }


    public int Id { get; set; }

    public int UzytkownikId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Koszyk_Podzespol> Koszyk_Podzespol { get; set; }

    public virtual Uzytkownicy Uzytkownicy { get; set; }

}

}
