
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EntityFrameworkModel
{

using System;
    using System.Collections.Generic;
    
public partial class Kategorie
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Kategorie()
    {

        this.Podzespoly = new HashSet<Podzespoly>();

    }


    public int Id { get; set; }

    public string Nazwa { get; set; }

    public string Obraz { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Podzespoly> Podzespoly { get; set; }

}

}
