
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EntityFrameworkModel
{

using System;
    using System.Collections.Generic;
    
public partial class Koszyk_Podzespol
{

    public int KoszykId { get; set; }

    public int PodzespolId { get; set; }

    public short Ilosc { get; set; }



    public virtual Koszyk Koszyk { get; set; }

    public virtual Podzespoly Podzespoly { get; set; }

}

}
