
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EntityFrameworkModel
{

using System;
    using System.Collections.Generic;
    
public partial class Podzespoly_Cechy
{

    public int CechyId { get; set; }

    public int PodzespolyId { get; set; }

    public string Wartosc { get; set; }



    public virtual Cechy Cechy { get; set; }

    public virtual Podzespoly Podzespoly { get; set; }

}

}
