//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SklepInternetowy : DbContext
    {
        public SklepInternetowy()
            : base("name=SklepInternetowy")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategorie> Kategorie { get; set; }
        public virtual DbSet<Koszyk> Koszyk { get; set; }
        public virtual DbSet<Koszyk_Podzespol> Koszyk_Podzespol { get; set; }
        public virtual DbSet<Podzespoly> Podzespoly { get; set; }
        public virtual DbSet<Uzytkownicy> Uzytkownicy { get; set; }
        public virtual DbSet<Cechy> Cechy { get; set; }
        public virtual DbSet<Podzespoly_Cechy> Podzespoly_Cechy { get; set; }
    }
}
